### ISSUE TITLE
EmbASP C# Unity 

### ISSUE THREAD

**Issue by RJrodrigo** [DeMaCS-UNICAL/EmbASP#55]
Hello, I have been attempting to use latest dev version (C# 6) in Unity (2019.3.2f1).

1. To use the Framework, what are the files that I should import into Unity? After building the project (EmbASP-CSharp-master) in Visual Studio 2017, should I only import?:

   bin/Debug/EmbASP.dll
   bin/Debug/Antlr4.Runtime.Standard.dll
   bin/Debug/Microsoft.VisualStudio.TestPlatform.TestFramework.dll

2. What are the supported versions of clingo.exe, dlv.exe, etc?

I have successfully used the version (3.5) provided in the Pac-man demo.
3. Would it be easy to migrate from version (3.5) when a C# release is available?

Kudos to everyone who put the framework together.

**Comment by stefanogermano** [comment]
We report here what we replied to your email a few weeks ago, because it might be useful to someone else.


> To use the Framework, what are the files that I should import into Unity? After building the project (EmbASP-CSharp-master) in Visual Studio 2017, should I only import?:
> bin/Debug/EmbASP.dll
> bin/Debug/Antlr4.Runtime.Standard.dll
> bin/Debug/Microsoft.VisualStudio.TestPlatform.TestFramework.dll

After building EmbASP, you need to import only the `bin/Debug/EmbASP.dll` into your Unity project. All the other `.dll` files are not necessary.


> What are the supported versions of clingo.exe, dlv.exe, etc?

**EmbASP** is completely independent from the versions of the ASP systems and solvers (clingo, dlv2, dlv). This means that you can use whatever version of the solver you prefer as long as a specialization for them exists.
We tried several different versions of the solvers, and they all worked fine.


> I have successfully used the version (3.5) provided in the Pac-man demo.
> 3. Would it be easy to migrate from version (3.5) when a C# release is available?

Usually, migration to a newer version does not require too much effort, by the way, I would suggest you use the EmbASP version you compiled yourself because it contains all the latest updates and, by default, it uses a newer version of .NET Framework (v4.6.1).

**Comment by RjRDRG** [comment]
If i only import the `bin/Debug/EmbASP.dll` this error appears:

![asperror](https://user-images.githubusercontent.com/37331667/81478300-47cf7180-9214-11ea-9cc5-c2d8bc78d423.png)

**Comment by stefanogermano** [comment]
The DLL of our latest release should contain everything needed to run EmbASP

https://github.com/DeMaCS-UNICAL/EmbASP/releases/tag/v6.0.0

Let us know if you have any problem with it

P.S. next time reopen the issue 😉
